name: Rust

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: moonrepo/setup-rust@v1
    - run: cargo test

  check-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: moonrepo/setup-rust@v1
    - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: moonrepo/setup-rust@v1
    - run: cargo clippy -- -D warnings